<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="EPiServer" />
    <Using Include="EPiServer.Core" />
    <Using Include="EPiServer.DataAbstraction" />
    <Using Include="EPiServer.DataAnnotations" />
  </ItemGroup>
  
  <ItemGroup>
	<PackageReference Include="EPiServer.CMS" />
	<PackageReference Include="EPiServer.Cms.UI.AspNetIdentity" />
	<PackageReference Include="Wangkanai.Detection" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*" />
  </ItemGroup>
</Project>
