<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="EPiServer" />
    <Using Include="EPiServer.Core" />
    <Using Include="EPiServer.DataAbstraction" />
    <Using Include="EPiServer.DataAnnotations" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="EPiServer.CMS" />
    <PackageReference Include="EPiServer.Cms.UI.AspNetIdentity" />
    <PackageReference Include="Wangkanai.Detection" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Infrastructure\LocalDb\Databases\Scripts\EPiServer.Cms.Core.sql" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Delaware.Optimizely.Sitemap.Core\Delaware.Optimizely.Sitemap.Core.csproj" />
    <ProjectReference Include="..\..\src\Delaware.Optimizely.Sitemap\Delaware.Optimizely.Sitemap.csproj" />
  </ItemGroup>
</Project>
