<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Storage.DataMovement.Blobs" Version="12.1.0" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />    
    <PackageVersion Include="EPiServer.CMS" Version="13.0.2" />
    <PackageVersion Include="EPiServer.CMS.UI.AspNetIdentity" Version="13.0.2" />
    <PackageVersion Include="EPiServer.CMS.UI.Core" Version="13.0.2" />
    <PackageVersion Include="EPiServer.Events" Version="13.0.2" />
    <PackageVersion Include="EPiServer.OptimizelyIdentity" Version="1.0.4" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageVersion Include="Microsoft.SourceLink.AzureRepos.Git" Version="10.0.203" />
    <PackageVersion Include="Moq" Version="4.17.2" />
	<PackageVersion Include="Wangkanai.Detection" Version="8.7.0" />
  </ItemGroup>
</Project>