<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing">
			<!--
				Disable MSBuild customizations from this package — they do not support
				separate build and publish operations used in CI.
			-->
			<ExcludeAssets>build; buildMultitargeting; buildTransitive;</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="MSTest.TestFramework" />
	</ItemGroup>

</Project>
