name: Dlw.Optimizely.SDS.CI

on:
    # Run CI on each PR.
    # Default types are 'opened', 'synchronize', and 'reopened'.
    pull_request:
        branches:
            - "main"
            - "master"
            - "releases/**"
            - "prereleases/**"

    # Run whenever we push to main, master or release branch.
    push:
        branches:
            - "main"
            - "master"
            - "releases/**"
            - "prereleases/**"

    # Allow manual triggering of the workflow with parameters.
    workflow_dispatch:
        inputs:
            noTests:
                description: "Skip tests."
                type: boolean
                default: false
            prerelease:
                description: "Pre-release to trigger preparing packages."
                type: string
                default: "none"

    merge_group:

env:
    MSSQL_SA_PASSWORD: ABCDefgh1234#!$%

jobs:
    build:
        name: "Build and Publish"
        runs-on: ubuntu-latest
        services:
            mssql:
                image: mcr.microsoft.com/mssql/server:2022-latest
                ports:
                    - 1433:1433
                env:
                    ACCEPT_EULA: Y
                    # Password needs to match complexity rules: https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16
                    # At least 2 uppercase chars, 2 lowercase chars, 2 digits, 2 non-alphanumerics
                    MSSQL_SA_PASSWORD: ${{ env.MSSQL_PASSWORD }}
                    MSSQL_PID: Developer
        steps:
            - uses: actions/checkout@v5

            - uses: delawarePro/platina-scripts/github/actions/ci.branch.conventions@refs/tags/2.6.0
              id: "conventions"
              with:
                  noTests: ${{ inputs.noTests }}
                  prerelease: ${{ inputs.prerelease }}

            - uses: delawarePro/platina-scripts/github/actions/dotnet-ci@refs/tags/2.6.0
              with:
                  noTests: ${{ steps.conventions.outputs.noTests }}
                  prerelease: ${{ steps.conventions.outputs.prerelease }}
                  withPack: "true"
                  withRelease: ${{ steps.conventions.outputs.withRelease }}
                  # Whether to allow dotnet publish and add it to pipeline artifacts.
                  withPublish: true
                  nuGetSourceUrl: ${{ vars.PLATINA_NUGET_FEED_URL }}
                  nuGetAuthToken: ${{ secrets.PLATINA_FEED_TOKEN }}